/**
 * @workagent/shared - 跨前后端共享模块入口
 * 导出所有类型、事件协议、错误码和常量
 */

// 核心类型
export type {
  AgentMode,
  PlanPhase,
  ToolSafety,
  ToolMode,
  PermissionDecision,
  ToolCall,
  ToolContext,
  MessageRole,
  MessageEventType,
  Message,
  UserInput,
  Attachment,
  PlanStatus,
  PlanStep,
  PlanOutline,
  Plan,
  ConversationContext,
  AgentState,
  ChunkMetadata,
  RetrievedChunk,
  SearchOptions,
  ExtractedDocument,
  DocumentSection,
  ModelInfo,
  ModelConfig,
  IndexJobStatus,
  IndexJob,
  MemoryType,
  Memory,
  ContextBudget,
  ToolResultRetention,
  RunTerminalReason,
  CompactBoundary,
  PromptDiagnostics,
  KnowledgeSearchResponse,
  Workspace,
  AgentRun,
  AgentEventRecord,
} from './types.js';

// 事件协议
export type {
  AgentEventEnvelope,
  AgentEventType,
  TokenEventData,
  ThinkingEventData,
  ToolStartEventData,
  ToolResultEventData,
  ToolSummaryEventData,
  PlanGeneratedEventData,
  PlanStepUpdateEventData,
  ModeChangeEventData,
  ModeSuggestionEventData,
  PhaseChangeEventData,
  CompactEventData,
  CompactBoundaryEventData,
  CitationEventData,
  RagEnrichEventData,
  PermissionRequestEventData,
  PermissionResultEventData,
  IndexProgressEventData,
  RunStatusEventData,
  DraftReadyEventData,
  DocReadyEventData,
  ModelPullProgressEventData,
  ErrorEventData,
  RecoverableErrorEventData,
  AgentEventDataMap,
  AgentEvent,
  RendererRequest,
} from './events.js';

// 错误体系
export {
  AgentError,
  OllamaConnectionError,
  ContextLengthExceededError,
  ModelNotAvailableError,
  ToolExecutionError,
  PermissionDeniedError,
  IndexJobError,
  FileParseError,
  SessionNotFoundError,
  getRecoveryStrategy,
  isOllamaError,
  isContextOverflowError,
} from './errors.js';

export type {
  RecoveryActionType,
  RecoveryStrategy,
} from './errors.js';

// 常量
export {
  APP_NAME,
  APP_VERSION,
  DATA_DIR_NAME,
  KNOWLEDGE_DIR_NAME,
  OLLAMA_DEFAULT_BASE_URL,
  OLLAMA_HEALTH_ENDPOINT,
  OLLAMA_CHAT_ENDPOINT,
  OLLAMA_EMBED_ENDPOINT,
  OLLAMA_PULL_ENDPOINT,
  OLLAMA_SHOW_ENDPOINT,
  OLLAMA_HEALTH_CHECK_INTERVAL,
  OLLAMA_STARTUP_TIMEOUT,
  OLLAMA_MAX_RESTART_ATTEMPTS,
  DEFAULT_CHAT_MODEL,
  DEFAULT_EMBEDDING_MODEL,
  FALLBACK_EMBEDDING_MODEL,
  REQUIRED_OLLAMA_MODELS,
  MODEL_ALIASES,
  isModelAvailable,
  BGE_M3_DIMENSIONS,
  DEFAULT_CONTEXT_LENGTH,
  COMPACT_THRESHOLD,
  COMPACT_KEEP_RECENT_MESSAGES,
  MAX_TOOL_RESULT_TOKENS,
  TOOL_EXECUTION_TIMEOUT,
  DEFAULT_RAG_TOP_K,
  MAX_RAG_INJECT_CHUNKS,
  RAG_CHUNK_CHAR_RANGE,
  CHUNK_SIZE,
  CHUNK_OVERLAP,
  INDEX_JOB_POLL_INTERVAL,
  SSE_RECONNECT_INTERVAL,
  PROCESS_CHECK_INTERVAL,
  SUPPORTED_FILE_TYPES,
  SUPPORTED_FILE_EXTENSIONS,
  LEGACY_FILE_TYPES,
  LEGACY_FORMAT_HINT,
  APP_DATA_RELATIVE_PATH,
  DB_FILENAME,
  VECTORS_DIR_NAME,
  OUTPUT_DIR_NAME,
  LOGS_DIR_NAME,
  TEMPLATES_DIR_NAME,
} from './constants.js';
